version: 1.0.0.{build}.{branch}
image: Visual Studio 2017
platform: Any CPU
before_build:
- cmd: nuget restore
after_build:
- cmd: 7z a Telegram.Bots.Toolkit.%APPVEYOR_BUILD_VERSION%.%APPVEYOR_REPO_COMMIT%.zip %APPVEYOR_BUILD_FOLDER%\Telegram.Bots.Toolkit\bin\Debug\*
build:
  verbosity: minimal
artifacts:
- path: Telegram.Bots.Toolkit.%APPVEYOR_BUILD_VERSION%.%APPVEYOR_REPO_COMMIT%.zip
deploy:
- provider: FTP
  host: ftp.winten.tk
  protocol: ftp
  username: u839111123
  password:
    secure: VY3WNeuXMq1nMcFp6BBZ6g==
  folder: /files/appveyor/Telegram.Bots.Toolkit
- provider: GitHub
  auth_token:
    secure: 9YQfKJraI5dDWvUsh48iWVFI9jBrNT2Fswv7PhHmmuyrXdQTG8YgB1FX4nqu058l
  draft: false
  force_update: true
  on:
    branch: master
- provider: GitHub
  auth_token:
    secure: 9YQfKJraI5dDWvUsh48iWVFI9jBrNT2Fswv7PhHmmuyrXdQTG8YgB1FX4nqu058l
  prerelease: true
  force_update: true
  on:
    branch: nightly
