version: 1.0.0.{build}.{branch}
image: Visual Studio 2017
platform: Any CPU
before_build:
- cmd: nuget restore
after_build:
- cmd: 7z a Telegram.Bots.Toolkit.{version}.zip %APPVEYOR_BUILD_FOLDER%\bin\Debug\*
build:
  verbosity: minimal
artifacts:
  # pushing a single file
  - path: Telegram.Bots.Toolkit.{version}.zip
