version: 1.0.0.{build}.{branch}
image: Visual Studio 2017
platform: Any CPU
before_build:
- cmd: nuget restore
after_build:
- cmd: 7z a Telegram.Bots.Toolkit.{build}.{branch}.APPVEYOR_REPO_COMMIT.zip %APPVEYOR_BUILD_FOLDER%\Telegram.Bots.Toolkit\bin\Debug\*
build:
  verbosity: minimal
artifacts:
  - path: Telegram.Bots.Toolkit.{build}.{branch}.APPVEYOR_REPO_COMMIT.zip
